;; Peak memory of the java.util.zip streams: compressing or decompressing 100 MB
;; must peak no more than 2 MB above doing 1 MB (spec, Acceptance Criteria →
;; Classes). The input is generated a 64 KiB block at a time and the output is
;; counted, never held, so only the streams can grow the heap.
;;
;; Two readings, both judged, because each is blind to what the other sees
;; (host/chez/rt.ss, bytes-allocated and current/maximum-memory-bytes):
;;   - the live heap (jolt.host/bytes-allocated after a collection), sampled
;;     sixteen times while each arm runs and kept at its highest. This sees a
;;     stream that keeps what it reads or writes. It does not see a transient: a
;;     block taken and dropped between two samples leaves no trace.
;;   - the collector's high-water mark (jolt.host/maximum-memory-bytes, what the
;;     spec's Tests section names), which is memory held from the OS. This sees a
;;     transient, because the footprint it records never shrinks. It cannot
;;     answer the 2 MB question: it grows in segments and hides anything under
;;     one collection trip (jolt.host/gc-trip-bytes, 16 MB here), so it is judged
;;     against two trips, which a real arm never reaches.
;; A gate that judged only the mark passed a decompressing stream that kept every
;; block (+0 KB); a gate that judged only the live heap passed a stream that took
;; a 40 MB transient (+404 MB of mark). Both were found by review of this commit,
;; 2026-09-15.
;;
;; Neither reading counts foreign memory. A stream's zlib buffers are foreign and
;; fixed in size (host/chez/java/zlib.ss), so a change that sized one to the whole
;; input would pass this gate; the corpus round trips would have to catch it.
;;
;; The control arm keeps the same 64 KiB blocks a leaking stream would keep, and
;; must read the 100 MB it holds, so a reading of zero is not a blind one.
;; The copy arms hold the same line for the byte copies jolt.fs's unzip and
;; gunzip run on: Files/copy from an InputStream to a Path and from a Path to an
;; OutputStream, and io/copy from an InputStream to an OutputStream. Each read
;; whole into one bytevector before this gate (review of 2026-09-18); the JDK
;; copies through an 8 KiB buffer. The source stream is generated and ticks as
;; it is read, so the live reading samples inside the one call.
;; Run: target/release/jolt run test/zip_memory_test.clj
(def mb (* 1024 1024))
(def slack (* 2 mb))
;; sixteen samples an arm, so the 1 MB and 100 MB arms are read alike
(def samples 16)

(def block
  (let [b (byte-array 65536)]
    (dotimes [i 65536] (aset-byte b i (unchecked-byte (mod i 251))))
    b))

(defn- fail! [& parts]
  (println (apply str "FAIL zip-memory: " parts))
  (System/exit 1))

(defn- live-bytes
  "The live heap, after a collection that must really happen: Chez refuses to
  collect while other threads run, and System/gc swallows the refusal."
  []
  (let [before (jolt.host/gc-count)]
    (System/gc)
    (when (= before (jolt.host/gc-count))
      (fail! "System/gc did not collect, so the live reading means nothing"))
    (jolt.host/bytes-allocated)))

(defn- step-for
  "Blocks between samples, so an arm of N bytes is read `samples` times."
  [n]
  (max 1 (quot (quot n 65536) samples)))

(defn- live-peak
  "The most the live heap held above its collected start while F ran. F is given
  a tick to call as it works; each tick collects and reads."
  [f]
  (let [base (live-bytes)
        peak (atom 0)
        tick (fn [] (swap! peak max (- (live-bytes) base)))]
    (f tick)
    @peak))

(defn- mark-growth
  "How far the collector's footprint rose while F ran: memory held from the OS,
  which never shrinks, so a transient shows here and nowhere else."
  [f]
  (System/gc)
  (jolt.host/reset-maximum-memory-bytes!)
  (let [base (jolt.host/current-memory-bytes)]
    (f (fn []))
    (- (jolt.host/maximum-memory-bytes) base)))

(defn- compress!
  "Gzip N generated bytes to PATH through GZIPOutputStream."
  [n path tick]
  (let [step (step-for n)]
    (with-open [o (java.util.zip.GZIPOutputStream. (java.io.FileOutputStream. path) 65536)]
      (loop [left n i 0]
        (if (pos? left)
          (let [k (min left 65536)]
            (.write o block 0 k)
            (when (zero? (mod i step)) (tick))
            (recur (- left k) (inc i)))
          ;; inside with-open: after the close, whatever the stream held is gone
          (tick))))))

(defn- decompress!
  "Gunzip PATH through GZIPInputStream; the count of bytes read. N is what the
  file holds, for the sampling step."
  [path n tick]
  (let [step (step-for n)]
    (with-open [in (java.util.zip.GZIPInputStream. (java.io.FileInputStream. path) 65536)]
      (let [buf (byte-array 65536)]
        (loop [total 0 i 0]
          (let [k (.read in buf 0 65536)]
            (if (neg? k)
              (do (tick) total)
              (do (when (zero? (mod i step)) (tick))
                  (recur (+ total k) (inc i))))))))))

(defn- generated-stream
  "An InputStream of N generated bytes that calls TICK every STEP reads."
  [n tick]
  (let [left (atom n) reads (atom 0) step (step-for n)]
    (proxy [java.io.InputStream] []
      (read
        ([] (if (pos? @left)
              (do (swap! left dec) (int (bit-and (aget block (mod @left 65536)) 0xff)))
              -1))
        ([arr off len]
         (if (pos? @left)
           (let [k (min len @left 65536)]
             (System/arraycopy block 0 arr off k)
             (swap! left - k)
             (swap! reads inc)
             (when (zero? (mod @reads step)) (tick))
             k)
           (do (tick) -1)))))))

(defn- counting-stream
  "An OutputStream that counts what it is given and calls TICK every STEP writes."
  [n counter tick]
  (let [writes (atom 0) step (step-for n)]
    (proxy [java.io.OutputStream] []
      (write
        ([b] (if (bytes? b) (swap! counter + (alength ^bytes b)) (swap! counter inc)))
        ([arr off len]
         (swap! counter + len)
         (swap! writes inc)
         (when (zero? (mod @writes step)) (tick)))))))

(defn- copy-in-to-path!
  "Files/copy of N generated bytes into PATH; the count answered."
  [n path tick]
  (java.nio.file.Files/copy (generated-stream n tick) (java.nio.file.Path/of path (into-array String []))
                            (into-array java.nio.file.CopyOption [java.nio.file.StandardCopyOption/REPLACE_EXISTING])))

(defn- copy-path-to-out!
  "Files/copy of PATH (N bytes) into a counting stream; the count answered."
  [path n tick]
  (let [counter (atom 0)]
    (java.nio.file.Files/copy (java.nio.file.Path/of path (into-array String [])) (counting-stream n counter tick))
    @counter))

(defn- copy-io!
  "io/copy of N generated bytes into a counting stream; the count answered."
  [n tick]
  (let [counter (atom 0)]
    (clojure.java.io/copy (generated-stream n tick) (counting-stream n counter tick))
    @counter))

(defn- judge [label small large mark]
  (let [ceiling (* 2 (jolt.host/gc-trip-bytes))]
    (println (format "zip-memory %s: 1 MB live +%d KB, 100 MB live +%d KB (slack %d KB; 100 MB mark +%d KB, ceiling %d KB)"
                     label (quot small 1024) (quot large 1024) (quot slack 1024)
                     (quot mark 1024) (quot ceiling 1024)))
    (when (> large (+ small slack))
      (fail! label " holds " (quot (- large small) 1024) " KB more than the 1 MB run"))
    (when (> mark ceiling)
      (fail! label " raised the footprint by " (quot mark 1024)
             " KB, past two collection trips: a transient the live reading cannot see"))))

(defn -main [& _]
  (let [tmp (System/getProperty "java.io.tmpdir")
        stamp (str (System/currentTimeMillis) "-" (rand-int 1000000))
        small (str tmp "/jolt-zip-memory-1-" stamp ".gz")
        large (str tmp "/jolt-zip-memory-100-" stamp ".gz")
        plain (str tmp "/jolt-zip-memory-copy-" stamp ".bin")
        hundred (* 100 mb)]
    (try
      ;; The yardstick: 100 MB kept as the blocks a leaking stream would keep.
      ;; The last sample falls before the end, so it sees most of them, not all.
      (let [held (live-peak (fn [tick]
                              (let [step (step-for hundred)]
                                (loop [kept [] left hundred i 0]
                                  (if (pos? left)
                                    (let [b (byte-array 65536)]
                                      (aset-byte b 0 (unchecked-byte (mod i 251)))
                                      (when (zero? (mod i step)) (tick))
                                      (recur (conj kept b) (- left 65536) (inc i)))
                                    (do (tick) (count kept)))))))]
        (when (< held (* 90 mb))
          (fail! "the control arm kept 100 MB in 64 KiB blocks and the reading rose only "
                 (quot held 1024) " KB, so this reading cannot see a stream that keeps them")))
      ;; values first: a fast wrong answer is not a pass
      (compress! mb small (fn []))
      (compress! hundred large (fn []))
      (when-not (and (= mb (decompress! small mb (fn []))) (= hundred (decompress! large hundred (fn []))))
        (fail! "a round trip did not give back the bytes it was given"))
      (judge "compress"
             (live-peak #(compress! mb small %))
             (live-peak #(compress! hundred large %))
             (mark-growth #(compress! hundred large %)))
      (judge "decompress"
             (live-peak #(decompress! small mb %))
             (live-peak #(decompress! large hundred %))
             (mark-growth #(decompress! large hundred %)))
      ;; the byte copies, values first
      (when-not (and (= mb (copy-in-to-path! mb plain (fn [])))
                     (= hundred (copy-in-to-path! hundred plain (fn [])))
                     (= hundred (copy-path-to-out! plain hundred (fn [])))
                     (= hundred (copy-io! hundred (fn []))))
        (fail! "a copy did not carry the bytes it was given"))
      (judge "Files/copy in->path"
             (live-peak #(copy-in-to-path! mb plain %))
             (live-peak #(copy-in-to-path! hundred plain %))
             (mark-growth #(copy-in-to-path! hundred plain %)))
      (judge "Files/copy path->out"
             (live-peak (fn [tick] (copy-in-to-path! mb plain (fn [])) (copy-path-to-out! plain mb tick)))
             (live-peak (fn [tick] (copy-in-to-path! hundred plain (fn [])) (copy-path-to-out! plain hundred tick)))
             (mark-growth #(copy-path-to-out! plain hundred %)))
      (judge "io/copy"
             (live-peak #(copy-io! mb %))
             (live-peak #(copy-io! hundred %))
             (mark-growth #(copy-io! hundred %)))
      (println "zip-memory: passed")
      (finally
        (jolt.host/delete-file! small)
        (jolt.host/delete-file! large)
        (jolt.host/delete-file! plain)))))

(-main)
