#!/bin/sh
# lock-check.sh — every lock in the runtime must route through jolt's wrapper.
#
# WHY THIS GATE EXISTS. A fiber suspended while holding an OS mutex loses mutual
# exclusion either way: if the switch unwinds, the lock is released
# mid-section; if it does not, the fiber keeps a mutex while another fiber on
# the SAME carrier runs, and Chez mutexes are recursive per thread, so that
# fiber's acquire succeeds anyway. Preemption is therefore refused while a lock
# is held, which only works if the runtime can TELL. It can only tell if every
# acquisition goes through the counting wrapper.
#
# A wrapper nobody is obliged to use decays back into the hand-marked scheme it
# replaced — which is exactly how the previous mechanism kept missing regions,
# one tightened quantum at a time. So the obligation is checked here rather than
# documented and hoped for.
#
# condition-wait is scanned for the SAME reason one lock over (jolt-x1no). It
# blocks the calling thread, and on a carrier that is every fiber placed on it,
# so a fiber reaching one stops siblings it cannot see — and if the thing that
# would end the wait is one of them, forever. The runtime has two waits now:
# jolt-condition-wait, which refuses on a fiber, and jolt-cv-wait, which parks a
# fiber and blocks a thread. Both live in locks.ss, so a bare condition-wait
# anywhere else is a site that has not chosen, which is how twelve of them came
# to block: each one was correct for the threads it was written for and nobody
# revisited them when fibers arrived.
#
# The scan covers the mutex PRIMITIVES and condition-wait, and nothing else. It used to also
# scan monitor-enter!/monitor-exit! by name, because jolt-with-monitor is the
# user-facing `locking` and therefore jolt's analogue of the `synchronized` case
# that pinned Loom's virtual threads until JEP 491. Those two now take their
# mutex through the wrapper (jolt-with-mutex, over the monitor's bookkeeping lock
# — ownership itself is a field, see concurrency.ss), so scanning them was
# scanning a wrapper rather than a primitive, and it left two entries on the
# allowlist that could never go to zero. They are covered transitively and
# strictly: rewriting either of them to grab the mutex directly shows up here as
# a new bare mutex-acquire in concurrency.ss. Mutation-verified in that
# direction, not assumed.
#
#   sh host/chez/lock-check.sh          check against the allowlist
#   sh host/chez/lock-check.sh --regen  regenerate it (review the diff!)
set -eu
cd "$(dirname "$0")/../.."

ALLOW=host/chez/lock-allowlist.txt
# The files that DEFINE the wrapper are where these primitives are supposed to
# appear. Everything else must go through it.
SANCTIONED='host/chez/locks.ss'

# THE SCANNED SET, as a decision rather than an accident of the glob. The two
# directories below are the hand-written runtime, which is all of it: the seed
# under host/chez/seed/ is generated by the compiler and contains no locks of its
# own, and host/scheme-adapter/ names these primitives only in its contract text
# and its port notes. Adding a hand-written runtime directory means adding it
# here.
#
# The pattern ends at a delimiter rather than a literal space, so a head wrapped
# onto its own line — (with-mutex\n  mu\n  body) — is seen. It used to require a
# space or a close paren, which is the spelling every site happens to use, so the
# hole only opened for someone wrapping a long lock expression. That is exactly
# the quiet kind: the gate would have gone on reporting zero.
PRIMS='(mutex-acquire|mutex-release|with-mutex|condition-wait)'

# COMMENTS ARE NOT CODE, and this gate reads text rather than data, so it has to
# say so. Everything from the first `;` on a line is dropped before matching, with
# line numbers preserved so a hit still reports its own line. Without it the header
# of any file that DISCUSSES one of these primitives becomes a finding — which
# condition-wait made immediate, since the rule about it is written out in prose in
# three files. The residual hole is a `;` inside a string literal ahead of a real
# call on the same line, which would hide that call; there is no such line, and the
# alternative is reading Scheme as data, which is what host/chez/park-lock-check.ss
# does for the check that needs structure.
strip_comments() { sed 's/;.*//' "$1"; }

scan() {
  for f in host/chez/*.ss host/chez/java/*.ss; do
    case " $SANCTIONED " in *" $f "*) continue ;; esac
    strip_comments "$f" \
      | grep -nE "\\($PRIMS([^a-zA-Z0-9!?*<>=/-]|\$)" 2>/dev/null \
      | while IFS=: read -r ln _; do
          # the matched fragment is "(<prim><delimiter>"; the second grep pulls
          # the name back out of it, whatever the delimiter turned out to be
          op=$(strip_comments "$f" | sed -n "${ln}p" \
                 | grep -oE "\\($PRIMS([^a-zA-Z0-9!?*<>=/-]|\$)" | head -1 \
                 | grep -oE "$PRIMS" | head -1)
          [ -n "$op" ] && echo "$f $op"
        done
  done | sort | uniq -c | awk '{print $2" "$3" "$1}' | sort
}

if [ "${1:-}" = "--regen" ]; then
  {
    echo "# host/chez/lock-allowlist.txt — generated. Regenerate with:"
    echo "#   sh host/chez/lock-check.sh --regen"
    echo "# Lines: <file> <primitive> <count>. A line whose count DROPS is stale"
    echo "# and fails the gate, so migrating a site to the wrapper must update this."
    echo "# Empty is the goal and the current state: every acquisition in the runtime
# routes through host/chez/locks.ss. A monitor counts transitively, through
# jolt-lock!, so it needs no entry here."
    scan
  } > "$ALLOW"
  echo "lock check: regenerated $(grep -cv '^#' "$ALLOW") entries"
  exit 0
fi

got=$(scan)
want=$(grep -v '^#' "$ALLOW" || true)

problems=$(
  # A NEW bare use, or MORE of them in a file than the allowlist records.
  echo "$got" | while read -r f op n; do
    [ -z "$f" ] && continue
    w=$(echo "$want" | awk -v f="$f" -v o="$op" '$1==f && $2==o {print $3}')
    if [ -z "$w" ]; then
      echo "  NEW bare lock use: $f $op ($n) — route it through host/chez/locks.ss"
    elif [ "$n" -gt "$w" ]; then
      echo "  MORE bare lock uses: $f $op ($w -> $n) — route them through host/chez/locks.ss"
    fi
  done
  # A line whose count DROPPED is stale: the migration happened but the
  # allowlist was not regenerated, which would let the count creep back unseen.
  echo "$want" | while read -r f op n; do
    [ -z "$f" ] && continue
    g=$(echo "$got" | awk -v f="$f" -v o="$op" '$1==f && $2==o {print $3}')
    g=${g:-0}
    if [ "$g" -lt "$n" ]; then
      echo "  STALE allowlist entry: $f $op ($n -> $g) — rerun with --regen"
    fi
  done
)

if [ -n "$problems" ]; then
  echo "$problems"
  echo "lock check: FAILED"
  exit 1
fi
echo "lock check: passed ($(echo "$got" | grep -c .) allowlisted sites, target is 0)"
