;; clojure.core.async.impl.protocols — the port protocol upstream's channel
;; types implement, for the ported code that asks about it.
;;
;; jolt's channels are native (host/chez/java/async.ss), so nothing here is
;; generated by a defprotocol over a channel type. A port asks one of two
;; questions — (:import (clojure.core.async.impl.protocols ReadPort)) and
;; (satisfies? clojure.core.async.impl.protocols/ReadPort ch) — and both need a
;; namespace to answer them, which is what this one is for.
;;
;; ReadPort alone is deliberate. It is the only name ported code imports from
;; here, and the protocol METHOD is never called: callers reach for
;; clojure.core.async/take! and friends directly. WritePort, Channel and
;; MAX-QUEUE-SIZE are upstream's too, and are not reproduced until something
;; needs them.
;;
;; No :require of clojure.core.async. Its vars are installed natively at boot
;; and the names below are spelled in full; a require would only close a cycle,
;; since the overlay (stdlib/clojure/core/async.clj) requires THIS namespace.
;; Upstream's file has the same shape, minus the cycle.
(ns clojure.core.async.impl.protocols
  (:require [jolt.host :as host]))

(defprotocol ReadPort
  (take! [port handler] "derefable val if taken, nil if take was enqueued"))

;; A channel reports the class name upstream's ManyToManyChannel has — that is
;; the class-arm in host/chez/java/async.ss — but the class graph carries no row
;; for the name, and value-host-tags, the list protocol dispatch looks a value up
;; by, is derived from that graph. Without a row, the extend-type below files its
;; impl under no tag a channel has and (satisfies? ReadPort ch) stays false.
;;
;; The supers list is empty on purpose: the class name is the only tag that earns
;; a place here, since dispatch looks up that same name. Naming the interfaces
;; upstream's class implements would not answer (instance? ReadPort ch) — that
;; goes through the instance check below — and nothing else asks.
(host/register-class-supers!
 "clojure.core.async.impl.channels.ManyToManyChannel" [])

;; (:import (clojure.core.async.impl.protocols ReadPort)) does not load a
;; namespace, and instance-check does not consult the class graph, so the key
;; (instance? ReadPort ch) lowers to has to be answered directly. Both spellings
;; are registered: the ns/Name key an unqualified symbol resolves to, and the
;; dotted class spelling.
;;
;; `when`, not the `and` it resembles. The registry reads nil as "not mine, ask
;; the next check" and anything non-nil as final, so an `and` — which returns
;; false for every name it does not own — would stop the walk and veto the
;; instance checks registered after this one (jolt.socket, jolt.time and
;; java.time all register checks).
(clojure.core/__register-instance-check!
 (fn [class-name val]
   (when (and (contains? #{"clojure.core.async.impl.protocols.ReadPort"
                           "clojure.core.async.impl.protocols/ReadPort"}
                         class-name)
              (clojure.core.async/chan? val))
     true)))

;; The method body is load-bearing, not decoration: extend-type with no methods
;; registers no impl at all, and satisfies? stays false.
(extend-type clojure.core.async.impl.channels.ManyToManyChannel
  ReadPort
  (take! [port f] (clojure.core.async/take! port f)))
